#!/usr/bin/env bash
path="$(realpath $@)";
ourHostname="$(hostname | cut -d "." -f1)";

fileOrFolder="--file-uri";
if [[ -d "$path" ]]; then
	fileOrFolder="--folder-uri";
fi

ssh -o StrictHostKeyChecking=no -p 2222 localhost \
	code ${fileOrFolder} vscode-remote://ssh-remote+${ourHostname}${path};

# Windows version
# ssh -o StrictHostKeyChecking=no -p 2222 localhost code --folder-uri vscode-remote://ssh-remote+dev-server-ec2-win/c:/users/brad.jones;
