#!/usr/bin/env bash

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

until valid_ip $defaultGatewayIp;
do
  defaultGatewayIp="$(/sbin/ip route | awk '/default/ { print $3 }')";
done

sed -i '/dom0\.wslhv\.local/d' /etc/hosts;
echo "${defaultGatewayIp} dom0.wslhv.local" >> /etc/hosts;
